### PR TITLE
Selman add user feature

### PR DESCRIPTION
**Pull request by suguz06**
Hello Guys,

I add my TC and edit some changes my features, step definitions and addUserPage class.

pls check

selman

### CODE REVIEW

**Comment by suguz06** [comment]
hello hello:))

can you hear me:) or see me:))

**Review by arhmcolak92 — APPROVED** [review]
Looks great Selman abi

**Comment by suguz06** [comment]
Thanks Abdurrahim, lets waits another guys to review before merge:))

**Review by iToniLo17 — APPROVED** [review]
Looks good!

**Pull request merged**
